version: "3"
services:
  app:
    build: ./FlaskForm/app
    links:
      - "db:database"
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: detail
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
